# Generated by Django 3.2.5 on 2021-07-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweetcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetcomment',
            old_name='writer',
            new_name='author',
        ),
    ]
